### ISSUE TITLE
Is this obsolete?

### ISSUE THREAD

**Issue by mavit** [goern/s2i-apache-httpd#1]
I see that `Dockerfile` says that the maintainer for this image is `SoftwareCollections.org <sclorg@redhat.com>`, but I notice that there’s another Apache HTTPD image over at https://github.com/sclorg/httpd-container.  Does that supersede this?  With so many different images available, it’s hard to know where’s the best place to start.

**Comment by goern** [comment]
True, you could use SCL's httpd. I will mark this repo as OBSOLETED.

First good point to start a search for an image is always access.redhat.com/containers, what ever you find out there has a very good chance of being supported by Red Hat, and the source being available at github at the same time... for example: https://access.redhat.com/containers#/registry.access.redhat.com/rhscl/httpd-24-rhel7
